### ISSUE TITLE
Make the frontend of registration page similar to login

### ISSUE THREAD

**Issue by ankit11hab** [ankit11hab/myBolooTeach#2]
Add CSS to the registration page and make it look similar to the login page.

**Comment by ratansen** [comment]
I want to work on this. Please assign me.

**Comment by Anurag-ravi** [comment]
I would like to work on this issue...

**Comment by ankit11hab** [comment]
Hi Anurag, thanks for commenting. This issue has already been resolved by @ratansen, you can check out the other issues and send me assign request.
