### ISSUE TITLE
Develop frontend of answer_form.html

### ISSUE THREAD

**Issue by ankit11hab** [ankit11hab/myBolooTeach#33]
The basic structure must not change, ie, the question and the form must be placed side by side.

**Comment by rohithbvs** [comment]
I'd like to work on this issue.

**Comment by rohithbvs** [comment]
I have done this, 
![WhatsApp Image 2021-12-06 at 10 53 50 AM](https://user-images.githubusercontent.com/54908694/144791951-6caea906-b1e3-4365-a9bf-487e1eb30a5f.jpeg)

if you have a good design idea in your mind can you tell me I will do that

**Comment by ankit11hab** [comment]
Great, kindly send me a pull request so that I can test it.
