### ISSUE TITLE
Make the frontend of profile_update.html similar to login page

### ISSUE THREAD

**Issue by ankit11hab** [ankit11hab/myBolooTeach#8]
If it is not possible to accommodate all the fields in that small area, divide the fields into two parts and take the input.

**Comment by Adityamaurya123uma** [comment]
Greeting, 
I am a beginner in open source contribution, but I am sure that I can perform this task . 
Can you please guide me through it. It would be awesome if you guide and let me contribute on this project.

**Comment by Soumadipdas18** [comment]
Hello,
Can you please assign it to me?

**Comment by ankit11hab** [comment]
This issue has been resolved by @Soumadipdas18 . Thanks a lot! @Adityamaurya123uma it will be really great if you work on the other issues of this project. Feel free to reach me out on discord.
